(function(){
  'use strict';
  const DEFAULT_CALC={rows:20,cols:12,data:{},styles:{},selected:'A1',sheetIndex:0,sheets:[{name:'Hoja 1',rows:20,cols:12,data:{},styles:{}}]};
  const O={
    app:'home', fileFilter:'all', fileSearch:'', calc:DEFAULT_CALC, slides:{items:[{title:'Título de la presentación',body:'Escribe el contenido de esta diapositiva.'}],selected:0}, chats:[{name:'Notas de TETORD',messages:[{from:'other',text:'Messenger local listo. Esta conversación permanece en este dispositivo.'}]}], chat:0,
    init(){
      this.shell=document.getElementById('officeShell'); if(!this.shell)return;
      this.calc=this.normalizeCalc(this.load('calc',this.calc)); this.slides=this.load('slides',this.slides); this.chats=this.load('messenger',this.chats);
      document.getElementById('officeLauncherBtn')?.addEventListener('click',()=>this.open('home'));
      document.getElementById('officeBackToWriterBtn')?.addEventListener('click',()=>this.close());
      this.shell.querySelectorAll('[data-office-app]').forEach(b=>b.addEventListener('click',()=>this.open(b.dataset.officeApp)));
      this.initCalc(); this.initSlides(); this.initMessenger(); this.initFiles(); this.initHome();
    },
    load(k,f){try{const v=localStorage.getItem('tetord.office.'+k);return v?JSON.parse(v):f}catch(_){return f}},
    save(k,v){try{localStorage.setItem('tetord.office.'+k,JSON.stringify(v))}catch(_){}},
    open(app){if(app==='writer'){this.close();return} this.app=app;document.body.classList.add('office-mode');document.body.classList.remove('office-calc-mode','office-slides-mode');if(app==='calc')document.body.classList.add('office-calc-mode');if(app==='slides')document.body.classList.add('office-slides-mode');this.shell.hidden=false;const map={home:'officeHome',files:'officeFiles',calc:'officeCalc',slides:'officeSlides',messenger:'officeMessenger'};Object.entries(map).forEach(([k,id])=>{const e=document.getElementById(id);if(e)e.hidden=k!==app});this.shell.querySelectorAll('[data-office-app]').forEach(b=>b.classList.toggle('is-active',b.dataset.officeApp===app));if(app==='home')this.renderHome();if(app==='files')this.renderFiles();if(app==='calc')this.renderCalc();if(app==='slides')this.renderSlides();if(app==='messenger')this.renderMessenger()},
    close(){document.body.classList.remove('office-mode','office-calc-mode','office-slides-mode');if(this.shell)this.shell.hidden=true;this.app='writer';this.shell?.querySelectorAll('[data-office-app]').forEach(b=>b.classList.toggle('is-active',b.dataset.officeApp==='writer'));window.MiWord?.Editor?.focus?.()},
    col(n){let s='';n++;while(n){let r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s},ref(c,r){return this.col(c)+(r+1)},
    normalizeCalc(v){
      const c=v&&typeof v==='object'?v:{}; const sheets=Array.isArray(c.sheets)&&c.sheets.length?c.sheets:[{name:'Hoja 1',rows:c.rows||20,cols:c.cols||12,data:c.data||{},styles:c.styles||{}}];
      sheets.forEach((s,i)=>{s.name=String(s.name||('Hoja '+(i+1)));s.rows=Math.max(1,Number(s.rows)||20);s.cols=Math.max(1,Number(s.cols)||12);s.data=s.data&&typeof s.data==='object'?s.data:{};s.styles=s.styles&&typeof s.styles==='object'?s.styles:{}});
      c.sheets=sheets;c.sheetIndex=Math.min(Math.max(0,Number(c.sheetIndex)||0),sheets.length-1);this.syncCalcSheet(c);return c;
    },
    syncCalcSheet(c=this.calc){const s=c.sheets[c.sheetIndex];c.rows=s.rows;c.cols=s.cols;c.data=s.data;c.styles=s.styles;c.selected=c.selected||'A1'},
    commitCalc(){const s=this.calc.sheets[this.calc.sheetIndex];s.rows=this.calc.rows;s.cols=this.calc.cols;s.data=this.calc.data;s.styles=this.calc.styles;this.save('calc',this.calc)},

    initHome(){
      document.getElementById('officeQuickWriter')?.addEventListener('click',()=>{this.close();window.MiWord?.DocumentManager?.newDocument?.()});
      document.getElementById('officeQuickCalc')?.addEventListener('click',()=>this.open('calc'));
      document.getElementById('officeQuickSlides')?.addEventListener('click',()=>this.open('slides'));
      document.getElementById('officeQuickFiles')?.addEventListener('click',()=>this.open('files'));
      document.getElementById('officeHomeRefresh')?.addEventListener('click',()=>this.renderHome());
    },
    initFiles(){
      document.getElementById('officeFilesRefresh')?.addEventListener('click',()=>this.renderFiles());
      document.getElementById('officeFilesSearch')?.addEventListener('input',e=>{this.fileSearch=e.target.value;this.renderFilesList()});
      document.querySelectorAll('[data-file-filter]').forEach(b=>b.addEventListener('click',()=>{this.fileFilter=b.dataset.fileFilter;document.querySelectorAll('[data-file-filter]').forEach(x=>x.classList.toggle('is-active',x===b));this.renderFilesList()}));
      document.getElementById('officeFilesNewWriter')?.addEventListener('click',()=>{this.close();window.MiWord?.DocumentManager?.newDocument?.()});
      document.getElementById('officeFilesNewCalc')?.addEventListener('click',()=>{this.calc=this.normalizeCalc({rows:20,cols:12,data:{},styles:{},selected:'A1',sheetIndex:0,sheets:[{name:'Hoja 1',rows:20,cols:12,data:{},styles:{}}]});this.save('calc',this.calc);this.open('calc')});
      document.getElementById('officeFilesNewSlides')?.addEventListener('click',()=>{this.slides={items:[{title:'Nueva presentación',body:'',theme:'miku',background:'#dceeff',image:null}],selected:0};this.save('slides',this.slides);this.open('slides')});
    },
    fileRecords(){
      const out=[];
      const docs=window.MiWord?.LocalDocuments?.load?.()||[];
      docs.forEach(d=>out.push({id:d.id,name:d.name||'Documento sin título',type:'writer',label:'Writer',updatedAt:d.updatedAt||'',format:(d.fileFormat||'html').toUpperCase(),action:()=>{if(!window.MiWord?.DocumentManager?.confirmDiscard?.())return;const doc=window.MiWord.LocalDocuments.get(d.id);if(!doc)return;window.MiWord.DocumentModel.replaceDocument({id:doc.id,name:doc.name,content:doc.content,saved:true,fileFormat:doc.fileFormat||'html',headerText:doc.headerText,footerText:doc.footerText,showPageNumber:doc.showPageNumber,differentFirstPage:doc.differentFirstPage,styles:doc.styles});window.MiWord.Editor.load(doc.content);window.MiWord.History.reset(window.MiWord.Editor.el.innerHTML);window.MiWord.PageView.syncDocumentDecorations();window.MiWord.TitleField.sync();this.close();window.MiWord.Editor.focus()}}));
      out.push({id:'office-calc',name:'Libro de cálculo',type:'calc',label:'Calc',updatedAt:this.load('calcMeta',{}).updatedAt||'',format:'LOCAL',action:()=>this.open('calc')});
      out.push({id:'office-slides',name:'Presentación',type:'slides',label:'Slides',updatedAt:this.load('slidesMeta',{}).updatedAt||'',format:'LOCAL',action:()=>this.open('slides')});
      return out.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));
    },
    renderHome(){
      const box=document.getElementById('officeHomeRecent'); if(!box)return; const rows=this.fileRecords().slice(0,6); box.innerHTML=rows.map((f,i)=>'<button type="button" class="office-recent-item office-recent-item--'+f.type+'" data-recent-index="'+i+'"><span class="office-recent-icon">'+({writer:'W',calc:'C',slides:'S'}[f.type]||'M')+'</span><span class="office-recent-main"><strong>'+this.esc(f.name)+'</strong><small>'+f.label+' · '+this.esc(f.format)+(f.updatedAt?' · '+new Date(f.updatedAt).toLocaleString():'')+'</small></span><span class="office-recent-arrow">›</span></button>').join('')||'<p class="office-empty">No hay archivos recientes todavía.</p>';box.querySelectorAll('[data-recent-index]').forEach(b=>b.addEventListener('click',()=>rows[Number(b.dataset.recentIndex)]?.action()));
    },
    renderFiles(){const input=document.getElementById('officeFilesSearch');if(input)input.value=this.fileSearch;this.renderFilesList();const status=document.getElementById('officeFilesStatus');if(status)status.textContent=this.fileRecords().length+' elemento'+(this.fileRecords().length===1?'':'s')+' local'+(this.fileRecords().length===1?'':'es')},
    renderFilesList(){
      const box=document.getElementById('officeFilesList');if(!box)return;const q=this.fileSearch.trim().toLowerCase();const rows=this.fileRecords().filter(f=>(this.fileFilter==='all'||f.type===this.fileFilter)&&(!q||f.name.toLowerCase().includes(q)));box.innerHTML=rows.map((f,i)=>'<button type="button" class="office-file-row office-file-row--'+f.type+'" data-file-index="'+i+'"><span class="office-file-icon">'+({writer:'W',calc:'C',slides:'S'}[f.type]||'M')+'</span><span class="office-file-main"><strong>'+this.esc(f.name)+'</strong><small>'+f.label+' · '+this.esc(f.format)+'</small></span><span class="office-file-date">'+(f.updatedAt?new Date(f.updatedAt).toLocaleString():'Sin fecha')+'</span><span class="office-file-open">Abrir</span></button>').join('')||'<p class="office-empty office-empty--large">No se encontraron archivos con estos filtros.</p>';box.querySelectorAll('[data-file-index]').forEach(b=>b.addEventListener('click',()=>rows[Number(b.dataset.fileIndex)]?.action()));
    },
    touchOfficeMeta(kind){this.save(kind+'Meta',{updatedAt:new Date().toISOString()})},
    initCalc(){
      document.getElementById('calcNewBtn')?.addEventListener('click',()=>{this.calc=this.normalizeCalc({rows:20,cols:12,data:{},styles:{},selected:'A1',sheetIndex:0,sheets:[{name:'Hoja 1',rows:20,cols:12,data:{},styles:{}}]});this.save('calc',this.calc);this.touchOfficeMeta('calc');this.renderCalc()});
      document.getElementById('calcAddRowBtn')?.addEventListener('click',()=>{this.calc.rows++;this.commitCalc();this.renderCalc()});
      document.getElementById('calcAddColBtn')?.addEventListener('click',()=>{this.calc.cols++;this.commitCalc();this.renderCalc()});
      document.getElementById('calcExportBtn')?.addEventListener('click',()=>this.exportCalc());
      document.getElementById('calcImportBtn')?.addEventListener('click',()=>document.getElementById('calcImportInput')?.click());
      document.getElementById('calcImportInput')?.addEventListener('change',e=>this.importCalc(e.target.files[0]));
      document.getElementById('calcFormulaInput')?.addEventListener('input',e=>{this.calc.data[this.calc.selected]=e.target.value;this.commitCalc();this.renderCalc(false)});
      document.getElementById('calcFormulaInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.renderCalc();const i=document.querySelector('#calcGrid input[data-ref="'+CSS.escape(this.calc.selected)+'"]');i?.focus()}});
      document.getElementById('calcSheets')?.addEventListener('click',e=>{const b=e.target.closest('[data-sheet-index]');if(!b)return;this.calc.sheetIndex=Number(b.dataset.sheetIndex);this.calc.selected='A1';this.syncCalcSheet();this.commitCalc();this.renderCalc()});
      document.getElementById('calcSheets')?.addEventListener('dblclick',e=>{const b=e.target.closest('[data-sheet-index]');if(!b)return;const idx=Number(b.dataset.sheetIndex),n=prompt('Nombre de la hoja',this.calc.sheets[idx].name);if(n&&n.trim()){this.calc.sheets[idx].name=n.trim().slice(0,40);this.commitCalc();this.renderCalc()}});
      document.getElementById('calcFillColor')?.addEventListener('input',e=>this.formatSelected({backgroundColor:e.target.value}));
      document.getElementById('calcNumberFormat')?.addEventListener('change',e=>this.formatSelected({numberFormat:e.target.value}));
      document.querySelectorAll('[data-calc-format]').forEach(b=>b.addEventListener('click',()=>this.formatSelected({[b.dataset.calcFormat]:true})));
      document.querySelectorAll('[data-calc-align]').forEach(b=>b.addEventListener('click',()=>this.formatSelected({align:b.dataset.calcAlign})));
      const add=document.getElementById('calcAddSheetBtn'); add?.addEventListener('click',()=>this.addSheet());
    },
    addSheet(){const n='Hoja '+(this.calc.sheets.length+1);this.calc.sheets.push({name:n,rows:20,cols:12,data:{},styles:{}});this.calc.sheetIndex=this.calc.sheets.length-1;this.syncCalcSheet();this.calc.selected='A1';this.commitCalc();this.renderCalc()},
    formatSelected(style){const ref=this.calc.selected;this.calc.styles[ref]={...(this.calc.styles[ref]||{}),...style};this.commitCalc();this.renderCalc(false)},
    formatValue(v,fmt){if(fmt==='currency'&&v!==''&&!isNaN(Number(v)))return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v));if(fmt==='percent'&&v!==''&&!isNaN(Number(v)))return (Number(v)*100).toFixed(2)+'%';if(fmt==='number'&&v!==''&&!isNaN(Number(v)))return new Intl.NumberFormat('es-MX',{maximumFractionDigits:6}).format(Number(v));return String(v)},
    value(ref,stack=[]){const raw=String(this.calc.data[ref]??'');if(raw.charAt(0)!=='=')return this.formatValue(raw,this.calc.styles[ref]?.numberFormat);if(stack.includes(ref))return '#CICLO!';let x=raw.slice(1).toUpperCase().trim();
      x=x.replace(/(SUM|AVERAGE|MIN|MAX|COUNT)\(([A-Z]+\d+):([A-Z]+\d+)\)/g,(_,fn,a,b)=>String(this.rangeFn(fn,a,b,stack.concat(ref))));
      x=x.replace(/IF\(([^,]+),([^,]+),([^\)]+)\)/g,(_,cond,a,b)=>{try{return Function('"use strict";return ('+this.replaceRefs(cond,stack.concat(ref))+')')()?a:b}catch(_){return b}});
      x=this.replaceRefs(x,stack.concat(ref));
      if(!/^[0-9+\-*/().%\s]+$/.test(x))return '#VALOR!';try{const v=Function('"use strict";return ('+x+')')();const out=Number.isFinite(v)?String(Math.round(v*1e10)/1e10):'#VALOR!';return this.formatValue(out,this.calc.styles[ref]?.numberFormat)}catch(_){return '#VALOR!'}},
    replaceRefs(x,stack){return x.replace(/([A-Z]+\d+)/g,(_,r)=>{const v=Number(this.value(r,stack));return Number.isFinite(v)?v:0})},
    rangeCells(a,b){const p=a.match(/^([A-Z]+)(\d+)$/),q=b.match(/^([A-Z]+)(\d+)$/);if(!p||!q)return[];const ci=s=>{let n=0;for(const c of s)n=n*26+c.charCodeAt(0)-64;return n-1};const out=[];for(let r=+p[2]-1;r<=+q[2]-1;r++)for(let c=ci(p[1]);c<=ci(q[1]);c++)out.push(this.ref(c,r));return out},
    rangeFn(fn,a,b,stack){const vals=this.rangeCells(a,b).map(r=>Number(this.value(r,stack))).filter(Number.isFinite);if(fn==='SUM')return vals.reduce((a,v)=>a+v,0);if(fn==='AVERAGE')return vals.length?vals.reduce((a,v)=>a+v,0)/vals.length:0;if(fn==='MIN')return vals.length?Math.min(...vals):0;if(fn==='MAX')return vals.length?Math.max(...vals):0;if(fn==='COUNT')return vals.length;return 0},
    renderSheets(){const box=document.getElementById('calcSheets');if(!box)return;box.innerHTML=this.calc.sheets.map((s,i)=>'<button type="button" role="tab" data-sheet-index="'+i+'" class="calc-sheet-tab '+(i===this.calc.sheetIndex?'is-active':'')+'">'+this.esc(s.name)+'</button>').join('')+'<button id="calcAddSheetBtn" class="calc-sheet-add" type="button" title="Agregar hoja">＋</button>';document.getElementById('calcAddSheetBtn').addEventListener('click',()=>this.addSheet())},
    renderCalc(focus=true){const t=document.getElementById('calcGrid');if(!t)return;this.syncCalcSheet();this.renderSheets();t.innerHTML='';let h='<thead><tr><th></th>';for(let c=0;c<this.calc.cols;c++)h+='<th>'+this.col(c)+'</th>';h+='</tr></thead><tbody>';for(let r=0;r<this.calc.rows;r++){h+='<tr><th>'+(r+1)+'</th>';for(let c=0;c<this.calc.cols;c++){const ref=this.ref(c,r),raw=this.calc.data[ref]??'',st=this.calc.styles[ref]||{},css='font-weight:'+(st.bold?'700':'400')+';font-style:'+(st.italic?'italic':'normal')+';text-align:'+(st.align||'left')+';background:'+(st.backgroundColor||'transparent')+';';h+='<td style="'+css+'"><input data-ref="'+ref+'" value="'+this.esc(raw)+'" title="'+ref+'"><span class="calc-value">'+this.esc(this.value(ref))+'</span></td>'}h+='</tr>'}t.innerHTML=h+'</tbody>';t.querySelectorAll('input').forEach(i=>{i.addEventListener('focus',()=>{this.calc.selected=i.dataset.ref;document.getElementById('calcNameBox').textContent=i.dataset.ref;document.getElementById('calcFormulaInput').value=this.calc.data[i.dataset.ref]??'';const st=this.calc.styles[i.dataset.ref]||{};document.getElementById('calcNumberFormat').value=st.numberFormat||'general';document.getElementById('calcFillColor').value=st.backgroundColor||'#fff3b8'});i.addEventListener('input',()=>{this.calc.data[i.dataset.ref]=i.value;this.commitCalc();document.getElementById('calcFormulaInput').value=i.value})});document.getElementById('calcStatus').textContent=this.calc.sheets[this.calc.sheetIndex].name+' · '+this.calc.cols+' × '+this.calc.rows;if(focus){const i=t.querySelector('input[data-ref="'+CSS.escape(this.calc.selected)+'"]');i?.focus()}}
    ,exportCalc(){const rows=[];for(let r=0;r<this.calc.rows;r++){const row=[];for(let c=0;c<this.calc.cols;c++){let v=String(this.calc.data[this.ref(c,r)]??'').replace(/"/g,'""');row.push(/[",\n]/.test(v)?'"'+v+'"':v)}rows.push(row.join(','))}this.download(this.calc.sheets[this.calc.sheetIndex].name+'.csv',rows.join('\n'),'text/csv')},
    async importCalc(file){if(!file)return;const lines=(await file.text()).split(/\r?\n/).filter(Boolean);const rows=Math.max(1,lines.length),cols=Math.max(1,...lines.map(x=>x.split(',').length));const sheet={name:file.name.replace(/\.[^.]+$/,'').slice(0,40)||'Importada',rows,cols,data:{},styles:{}};lines.forEach((line,r)=>line.split(',').forEach((v,c)=>sheet.data[this.ref(c,r)]=v.replace(/^"|"$/g,'').replace(/""/g,'"')));this.calc.sheets.push(sheet);this.calc.sheetIndex=this.calc.sheets.length-1;this.syncCalcSheet();this.save('calc',this.calc);this.touchOfficeMeta('calc');this.renderCalc()},
    initSlides(){document.getElementById('slideNewBtn')?.addEventListener('click',()=>{this.slides={items:[{title:'Nueva presentación',body:''}],selected:0};this.save('slides',this.slides);this.touchOfficeMeta('slides');this.renderSlides()});document.getElementById('slideAddBtn')?.addEventListener('click',()=>{this.slides.items.splice(this.slides.selected+1,0,{title:'Nueva diapositiva',body:''});this.slides.selected++;this.save('slides',this.slides);this.touchOfficeMeta('slides');this.renderSlides()});document.getElementById('slideDeleteBtn')?.addEventListener('click',()=>{if(this.slides.items.length===1)return;this.slides.items.splice(this.slides.selected,1);this.slides.selected=Math.max(0,this.slides.selected-1);this.save('slides',this.slides);this.touchOfficeMeta('slides');this.renderSlides()});document.getElementById('slideTitleInput')?.addEventListener('input',e=>{this.slides.items[this.slides.selected].title=e.target.value;this.save('slides',this.slides);this.touchOfficeMeta('slides');this.renderSlides(false)});document.getElementById('slideBodyInput')?.addEventListener('input',e=>{this.slides.items[this.slides.selected].body=e.target.value;this.save('slides',this.slides);this.touchOfficeMeta('slides');this.renderSlides(false)});document.getElementById('slidePresentBtn')?.addEventListener('click',()=>this.present());document.getElementById('slidePresentCloseBtn')?.addEventListener('click',()=>document.getElementById('slidePresentOverlay').hidden=true)},
    renderSlides(edit=true){const box=document.getElementById('slideThumbs');if(!box)return;box.innerHTML='';this.slides.items.forEach((s,i)=>{const b=document.createElement('button');b.className='slide-thumb'+(i===this.slides.selected?' is-active':'');b.type='button';b.innerHTML='<span>'+(i+1)+'</span><strong>'+this.esc(s.title||'Sin título')+'</strong><small>'+this.esc((s.body||'').slice(0,50))+'</small>';b.onclick=()=>{this.slides.selected=i;this.renderSlides()};box.appendChild(b)});if(edit){const s=this.slides.items[this.slides.selected];document.getElementById('slideTitleInput').value=s.title;document.getElementById('slideBodyInput').value=s.body}document.getElementById('slidesStatus').textContent='Presentación · '+this.slides.items.length+' diapositiva'+(this.slides.items.length===1?'':'s')},
    present(){const s=this.slides.items[this.slides.selected],c=document.getElementById('slidePresentCard');c.innerHTML='<h1>'+this.esc(s.title)+'</h1><div>'+this.esc(s.body).replace(/\n/g,'<br>')+'</div>';document.getElementById('slidePresentOverlay').hidden=false},
    initMessenger(){document.getElementById('messengerComposer')?.addEventListener('submit',e=>{e.preventDefault();const i=document.getElementById('messengerInput'),v=i.value.trim();if(!v)return;this.chats[this.chat].messages.push({from:'me',text:v,at:Date.now()});i.value='';this.save('messenger',this.chats);this.renderMessenger()});document.getElementById('messengerNewChatBtn')?.addEventListener('click',()=>{const n=prompt('Nombre de la conversación','Nueva conversación');if(!n)return;this.chats.push({name:n.slice(0,80),messages:[]});this.chat=this.chats.length-1;this.save('messenger',this.chats);this.renderMessenger()})},
    renderMessenger(){const list=document.getElementById('messengerChats'),msgs=document.getElementById('messengerMessages'),head=document.getElementById('messengerConversationHead');list.innerHTML='';this.chats.forEach((c,i)=>{const b=document.createElement('button');b.className='messenger-chat'+(i===this.chat?' is-active':'');b.type='button';b.innerHTML='<strong>'+this.esc(c.name)+'</strong><small>'+this.esc(c.messages.length?c.messages[c.messages.length-1].text:'Sin mensajes')+'</small>';b.onclick=()=>{this.chat=i;this.renderMessenger()};list.appendChild(b)});const c=this.chats[this.chat];head.innerHTML='<strong>'+this.esc(c.name)+'</strong><small>Conversación local</small>';msgs.innerHTML='';c.messages.forEach(m=>{const d=document.createElement('div');d.className='message-bubble message-bubble--'+(m.from==='me'?'me':'other');d.textContent=m.text;msgs.appendChild(d)});msgs.scrollTop=msgs.scrollHeight},
    esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))},
    download(name,text,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'}));a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
  };
  window.addEventListener('DOMContentLoaded',()=>O.init()); window.TETORDOffice=O;
})();

// TETORD 3.3 Slides PRO extensions
(() => {
  const O=window.TETORDOffice;
  if(!O)return;
  const blank=()=>({title:'Nueva diapositiva',body:'',theme:'miku',background:'#dceeff',image:''});
  O.slides = O.slides && O.slides.items ? O.slides : {items:[blank()],selected:0};
  O.slides.items=O.slides.items.map(s=>({...blank(),...s}));
  O._slideSave=function(){this.save('slides',this.slides)};
  O.initSlides=function(){
    document.getElementById('slideNewBtn')?.addEventListener('click',()=>{this.slides={items:[{...blank(),title:'Nueva presentación'}],selected:0};this._slideSave();this.renderSlides()});
    document.getElementById('slideAddBtn')?.addEventListener('click',()=>{this.slides.items.splice(this.slides.selected+1,0,blank());this.slides.selected++;this._slideSave();this.renderSlides()});
    document.getElementById('slideDuplicateBtn')?.addEventListener('click',()=>{const s=this.slides.items[this.slides.selected];this.slides.items.splice(this.slides.selected+1,0,JSON.parse(JSON.stringify(s)));this.slides.selected++;this._slideSave();this.renderSlides()});
    document.getElementById('slideDeleteBtn')?.addEventListener('click',()=>{if(this.slides.items.length===1)return;this.slides.items.splice(this.slides.selected,1);this.slides.selected=Math.max(0,this.slides.selected-1);this._slideSave();this.renderSlides()});
    ['slideTitleInput','slideBodyInput'].forEach(id=>document.getElementById(id)?.addEventListener('input',e=>{this.slides.items[this.slides.selected][id==='slideTitleInput'?'title':'body']=e.target.value;this._slideSave();this.renderSlides(false)}));
    document.getElementById('slideThemeSelect')?.addEventListener('change',e=>{this.slides.items[this.slides.selected].theme=e.target.value;this._slideSave();this.renderSlides(false)});
    document.getElementById('slideBgColor')?.addEventListener('input',e=>{this.slides.items[this.slides.selected].background=e.target.value;this._slideSave();this.renderSlides(false)});
    document.getElementById('slideImageBtn')?.addEventListener('click',()=>document.getElementById('slideImageInput')?.click());
    document.getElementById('slideImageInput')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{this.slides.items[this.slides.selected].image=r.result;this._slideSave();this.renderSlides(false)};r.readAsDataURL(f)});
    document.getElementById('slidePresentBtn')?.addEventListener('click',()=>this.present());
    document.getElementById('slidePresentCloseBtn')?.addEventListener('click',()=>document.getElementById('slidePresentOverlay').hidden=true);
    document.getElementById('slidePrevBtn')?.addEventListener('click',()=>this.slideNavigate(-1));document.getElementById('slideNextBtn')?.addEventListener('click',()=>this.slideNavigate(1));
    document.addEventListener('keydown',e=>{const o=document.getElementById('slidePresentOverlay');if(o?.hidden)return;if(e.key==='ArrowRight'||e.key===' '){e.preventDefault();this.slideNavigate(1)}if(e.key==='ArrowLeft'){e.preventDefault();this.slideNavigate(-1)}if(e.key==='Escape')o.hidden=true});
  };
  O.renderSlides=function(edit=true){const box=document.getElementById('slideThumbs');if(!box)return;box.innerHTML='';this.slides.items.forEach((s,i)=>{const b=document.createElement('button');b.className='slide-thumb'+(i===this.slides.selected?' is-active':'');b.type='button';b.innerHTML='<span>'+String(i+1)+'</span><strong>'+this.esc(s.title||'Sin título')+'</strong><small>'+this.esc((s.body||'').slice(0,50))+'</small>';b.onclick=()=>{this.slides.selected=i;this.renderSlides()};box.appendChild(b)});const s=this.slides.items[this.slides.selected];if(edit){document.getElementById('slideTitleInput').value=s.title;document.getElementById('slideBodyInput').value=s.body;document.getElementById('slideThemeSelect').value=s.theme||'miku';document.getElementById('slideBgColor').value=s.background||'#dceeff'}const c=document.getElementById('slideCanvas');c.className='slide-canvas theme-'+(s.theme||'miku');c.style.background=s.background||'';const img=document.getElementById('slideImagePreview');img.hidden=!s.image;if(s.image)img.src=s.image;document.getElementById('slidesStatus').textContent='Presentación · '+this.slides.items.length+' diapositiva'+(this.slides.items.length===1?'':'s')};
  O.present=function(){document.getElementById('slidePresentOverlay').hidden=false;this.renderPresent()};
  O.renderPresent=function(){const s=this.slides.items[this.slides.selected],c=document.getElementById('slidePresentCard');c.className='slide-present-card theme-'+(s.theme||'miku');c.style.background=s.background||'';c.innerHTML='<h1>'+this.esc(s.title)+'</h1><div class="slide-present-body">'+this.esc(s.body).replace(/\n/g,'<br>')+'</div>'+(s.image?'<img src="'+s.image+'" alt="Imagen de diapositiva">':'')};
  O.slideNavigate=function(delta){this.slides.selected=Math.max(0,Math.min(this.slides.items.length-1,this.slides.selected+delta));this.renderSlides(false);this.renderPresent()};
})();
